server:
  address: 192.168.1.104
  port: 8081

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  rabbitmq:
    host: 192.168.1.132
    port: 15672
    username: guest
    password: guest
    virtual-host: /
  application:
    name: hhh

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    instance-id: 192.168.1.104:8081
#    hostname: localhost:8081
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 5
#    registerWithEureka: false
#    fetchRegistry: false
    service-url:
      defaultZone: http://test:123456@192.168.1.104:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
