
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    instance-id: localhost:8770
  client:
    service-url:
      defaultZone: http://test:123456@localhost:8761/eureka/

spring:
  application:
    name: service-zuul-2

server:
  port: 8770

zuul:
  routes:
    api-product:
      path: /api-product/**
      serviceId: product

    api-hhh:
      path: /api-hhh/**
      serviceId: hhh
    api-config:
      path: /api-config/**
      serviceId: config-client
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  security:
    enabled: false